name: Unit tests
on:
  push:
    branches: ["main", "dev"]
  pull_request: 
    branches: ["main", "dev"]

jobs:
  test:
    strategy:
      matrix:
        config: [Debug, Release]
        os: [ubuntu-24.04, windows-2022]
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
      - name: Restore NuGet packages
        run: dotnet restore --locked-mode
      - name: Build project
        run: dotnet build --no-restore -c ${{ matrix.config }}
      - name: Run tests
        run: dotnet test --no-restore --no-build -c ${{ matrix.config }}
